<h1>Bemutatkozás</h1>
<hr class="my-4">
<p>Tisztelettel köszöntöm a kedves Látogatót a Dabasi Táncsics Mihály Gimnázium virtuális kapujában! Mielőtt még belépne rajta, engedje meg, hogy a gimnázium igazgatójaként néhány mondat erejéig segítségére legyek a tájékozódásban!</p>
<h3>Kinek ajánlom szíves figyelmébe iskolánk megújult honlapjának tanulmányozását?</h3>
<p>Mindenkinek, aki kereső szemmel, kíváncsi lélekkel vág neki az ismeretlennek, hogy felfedezzen egy új, számára eddig ismeretlen világot: iskolakeresésben fáradozó szülőknek éppúgy, mint továbbtanulni szándékozó diákoknak. Ajánlom azoknak is, akik otthonosan mozognak már az iskola falai között, hogy most már a virtuális térben is eligazodjanak: a napi ügyek, megoldandó problémák után érdeklődő szülőknek éppúgy, mint a kirándulások, a sportesemények, a tanulmányi versenyek emlékezetes pillanatait felidézni vágyó vagy éppen tananyag után kutató diákjainknak is.</p>
<p>Külön felhívom mindenki figyelmét a „Sikereink” menüpontra, amely folyamatos frissítés alatt áll. Mert mi mindenkire büszkék vagyunk, aki széles e hazában – és még azon túl is – öregbíti jóhírünket: legyen szó ping-pongról, gokartversenyről, fitt-kidről, röplabdáról, kézilabdáról vagy történelem OKTV-ről, Curie kémiaversenyről, Arany János szavalóversenyről… Tudniillik egy jó iskola leginkább a diákjairól ismerszik meg: minél színesebb, tevékenyebb és vállalkozóbb szellemű a közössége, annál különlegesebb, izgalmasabb az élete.</p>
<p>A honlapot úgy állítottuk össze, és úgy is gondozzuk, hogy minél több információ jusson el általa minden érdeklődőhöz, és ne csupán a tájékozódást szolgálja, hanem – lehetőség szerint – a napi ügyintézés és a tanulás eszközévé is válhasson. Reményeink szerint az iskola virtuális kapuján belépve mindenki megtalálja azt, amit keres: a legfrissebb híreket és az általános tudnivalókat; tanárainkat, munkatársainkat és diákjainkat; a tanulmányi munka részleteit és a TáDé (Táncsics Diákélet) valamennyi emlékezetes pillanatát.</p>
<p>Folyamatosan frissítjük a weboldalt és dolgozunk azért, hogy hiánytalan tartalommal találkozhasson!</p>
<p style="margin-bottom: 0; text-align: right;">Pásztor Gergely<br>igazgató</p>
